openapi: 3.1.0
info:
  title: Cloud Foundry V3 API
  description: |-
    # Welcome to the Cloud Foundry V3 API docs! Version 3 adds support for several key features:

    - Running one-off tasks on Cloud Foundry
    - Applications consisting of several processes via a Procfile
    - Direct access to application packages and droplets
    - Changing application source code without stopping the app via deployments

    # Getting help
    The CAPI team can most easily be reached on our Slack channel for questions and issues regarding the API. To report an issue with the docs or API, please feel free to file a GitHub issue on our API repo, cloud_controller_ng.
    We recommend reaching out to Slack first as we will be most responsive there.
        
    # More resources
    - The Cloud Foundry V2 API is still depricated but still available for interacting with Cloud Foundry.
    - Running Tasks
    - V3 API Documentation OpenAPI Spec Source Code.
  version: 3.x.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    email: cf-dev@lists.cloudfoundry.org
    name: Cloud Foundry CAPI Team
    url: https://cloudfoundry.slack.com/archives/C07C04W4Q
servers:
  - url: http://127.0.0.1:4010
    description: Prism mock server
paths:
  /:
    get:
      tags:
        - Root
      summary: Get root
      description: The Root endpoint provides the entry point for the Cloud Foundry API. It includes links to all the available resources and endpoints.
      operationId: getRoot
      security: []
      responses:
        '200':
          $ref: '#/components/responses/200Root'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '500':
          $ref: '#/components/responses/500InternalServerError'
components:
  securitySchemes:
    oauth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://uaa.cloudfoundry.local/api-oauth/dialog
          scopes:
            cloud_controller.admin: This scope provides read and write access to all resources
            cloud_controller.admin_read_only: This scope provides read only access to all resources
            cloud_controller.global_auditor: This scope provides read access to all resources
            cloud_controller.read: Read access to the Cloud Controller
            cloud_controller.write: Write access to the Cloud Controller
            cloud_controller.update_build_state: This scope allows its bearer to update the state of a build; currently only used when updating builds
            cloud_controller_service_permissions.read: This scope provides read only access for service instance permissions
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Bearer JWT token authentication
  schemas:
    link:
      type: object
      properties:
        href:
          type: string
          format: uri
          description: The URL of the link
        method:
          type: string
          description: An optional field containing the HTTP method to be used when following the URL
      required:
        - href
      description: |
        Each link is keyed by its type and will include a href for the URL and an optional method for links that cannot be followed using GET.
  responses:
    200Root:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              links:
                type: object
                properties:
                  self:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the current endpoint
                  apps:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Apps endpoint
                  buildpacks:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Buildpacks endpoint
                  builds:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Builds endpoint
                  deployments:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Deployments endpoint
                  domains:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Domains endpoint
                  droplets:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Droplets endpoint
                  environment_variable_groups:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Environment Variable Groups endpoint
                  feature_flags:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Feature Flags endpoint
                  info:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Info endpoint
                  isolation_segments:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Isolation Segments endpoint
                  jobs:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Jobs endpoint
                  organization_quotas:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Organization Quotas endpoint
                  organizations:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Organizations endpoint
                  packages:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Packages endpoint
                  processes:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Processes endpoint
                  resource_matches:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Resource Matches endpoint
                  roles:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Roles endpoint
                  routes:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Routes endpoint
                  security_groups:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Security Groups endpoint
                  service_brokers:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Service Brokers endpoint
                  service_credential_bindings:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Service Credential Bindings endpoint
                  service_instances:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Service Instances endpoint
                  service_offerings:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Service Offerings endpoint
                  service_plans:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Service Plans endpoint
                  service_plan_visibilities:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Service Plan Visibilities endpoint
                  service_route_bindings:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Service Route Bindings endpoint
                  service_usage_events:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Service Usage Events endpoint
                  sidecars:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Sidecars endpoint
                  space_quotas:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Space Quotas endpoint
                  spaces:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Spaces endpoint
                  stacks:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Stacks endpoint
                  tasks:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Tasks endpoint
                  users:
                    allOf:
                      - $ref: '#/components/schemas/link'
                      - description: Link to the Users endpoint
    401Unauthorized:
      description: Unauthorized
    403Forbidden:
      description: Forbidden
    500InternalServerError:
      description: Internal Server Error
